# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

prepare_eigen_statistics_cpp <- function(eigenvectors, eigenvalues, crossproduct) {
    .Call(`_BayesLinReg_prepare_eigen_statistics_cpp`, eigenvectors, eigenvalues, crossproduct)
}

build_scaled_eigen_factor_cpp <- function(eigenvectors, eigenvalues, predictor_scale, source_order) {
    .Call(`_BayesLinReg_build_scaled_eigen_factor_cpp`, eigenvectors, eigenvalues, predictor_scale, source_order)
}

blm_build_info_cpp <- function() {
    .Call(`_BayesLinReg_blm_build_info_cpp`)
}

draw_gig_rcpp_cpp <- function(n, lambda, chi, psi) {
    .Call(`_BayesLinReg_draw_gig_rcpp_cpp`, n, lambda, chi, psi)
}

blm_gibbs_rcpp_cpp <- function(y, X, residual_shape, residual_scale, iterations, burnin, thin, progress_callback, block_id, block_model, normal_shape, normal_scale, pi_alpha, pi_beta, spike_var_shape, spike_var_scale, global_scale, local_a, local_b, multi_gamma_list, multi_pi_alpha_list, multi_var_shape, multi_var_scale, learn_residual_var, fixed_residual_var, store_samples, store_coefficient_cov, effective_n, fit_intercept, intercept_x_mean, intercept_y_mean, use_sufficient_statistics, summary_XtX, summary_Xty, summary_yty, center_observations, residual_sse_offset, compute_pve, pve_type_code) {
    .Call(`_BayesLinReg_blm_gibbs_rcpp_cpp`, y, X, residual_shape, residual_scale, iterations, burnin, thin, progress_callback, block_id, block_model, normal_shape, normal_scale, pi_alpha, pi_beta, spike_var_shape, spike_var_scale, global_scale, local_a, local_b, multi_gamma_list, multi_pi_alpha_list, multi_var_shape, multi_var_scale, learn_residual_var, fixed_residual_var, store_samples, store_coefficient_cov, effective_n, fit_intercept, intercept_x_mean, intercept_y_mean, use_sufficient_statistics, summary_XtX, summary_Xty, summary_yty, center_observations, residual_sse_offset, compute_pve, pve_type_code)
}

blm_gibbs_sparse_rcpp_cpp <- function(residual_shape, residual_scale, iterations, burnin, thin, progress_callback, block_id, block_model, normal_shape, normal_scale, pi_alpha, pi_beta, spike_var_shape, spike_var_scale, global_scale, local_a, local_b, multi_gamma_list, multi_pi_alpha_list, multi_var_shape, multi_var_scale, learn_residual_var, fixed_residual_var, store_samples, store_coefficient_cov, effective_n, fit_intercept, intercept_x_mean, intercept_y_mean, summary_XtX, summary_center, summary_Xty, summary_yty, compute_pve, pve_type_code) {
    .Call(`_BayesLinReg_blm_gibbs_sparse_rcpp_cpp`, residual_shape, residual_scale, iterations, burnin, thin, progress_callback, block_id, block_model, normal_shape, normal_scale, pi_alpha, pi_beta, spike_var_shape, spike_var_scale, global_scale, local_a, local_b, multi_gamma_list, multi_pi_alpha_list, multi_var_shape, multi_var_scale, learn_residual_var, fixed_residual_var, store_samples, store_coefficient_cov, effective_n, fit_intercept, intercept_x_mean, intercept_y_mean, summary_XtX, summary_center, summary_Xty, summary_yty, compute_pve, pve_type_code)
}

blm_gibbs_block_rcpp_cpp <- function(residual_shape, residual_scale, iterations, burnin, thin, progress_callback, block_id, block_model, normal_shape, normal_scale, pi_alpha, pi_beta, spike_var_shape, spike_var_scale, global_scale, local_a, local_b, multi_gamma_list, multi_pi_alpha_list, multi_var_shape, multi_var_scale, learn_residual_var, fixed_residual_var, store_samples, store_coefficient_cov, effective_n, fit_intercept, intercept_x_mean, intercept_y_mean, summary_XtX, summary_indices, summary_types, summary_center, summary_Xty, summary_yty, compute_pve, pve_type_code, nthreads) {
    .Call(`_BayesLinReg_blm_gibbs_block_rcpp_cpp`, residual_shape, residual_scale, iterations, burnin, thin, progress_callback, block_id, block_model, normal_shape, normal_scale, pi_alpha, pi_beta, spike_var_shape, spike_var_scale, global_scale, local_a, local_b, multi_gamma_list, multi_pi_alpha_list, multi_var_shape, multi_var_scale, learn_residual_var, fixed_residual_var, store_samples, store_coefficient_cov, effective_n, fit_intercept, intercept_x_mean, intercept_y_mean, summary_XtX, summary_indices, summary_types, summary_center, summary_Xty, summary_yty, compute_pve, pve_type_code, nthreads)
}

blm_gibbs_ld_rcpp_cpp <- function(residual_shape, residual_scale, iterations, burnin, thin, progress_callback, block_id, block_model, normal_shape, normal_scale, pi_alpha, pi_beta, spike_var_shape, spike_var_scale, global_scale, local_a, local_b, multi_gamma_list, multi_pi_alpha_list, multi_var_shape, multi_var_scale, learn_residual_var, fixed_residual_var, store_samples, store_coefficient_cov, effective_n, fit_intercept, intercept_x_mean, intercept_y_mean, ld_blocks, ld_indices, ld_scale, summary_Xty, summary_yty, compute_pve, pve_type_code, nthreads) {
    .Call(`_BayesLinReg_blm_gibbs_ld_rcpp_cpp`, residual_shape, residual_scale, iterations, burnin, thin, progress_callback, block_id, block_model, normal_shape, normal_scale, pi_alpha, pi_beta, spike_var_shape, spike_var_scale, global_scale, local_a, local_b, multi_gamma_list, multi_pi_alpha_list, multi_var_shape, multi_var_scale, learn_residual_var, fixed_residual_var, store_samples, store_coefficient_cov, effective_n, fit_intercept, intercept_x_mean, intercept_y_mean, ld_blocks, ld_indices, ld_scale, summary_Xty, summary_yty, compute_pve, pve_type_code, nthreads)
}

blm_gibbs_eigen_block_rcpp_cpp <- function(residual_shape, residual_scale, iterations, burnin, thin, progress_callback, block_id, block_model, normal_shape, normal_scale, pi_alpha, pi_beta, spike_var_shape, spike_var_scale, global_scale, local_a, local_b, multi_gamma_list, multi_pi_alpha_list, multi_var_shape, multi_var_scale, learn_residual_var, fixed_residual_var, store_samples, store_coefficient_cov, effective_n, fit_intercept, intercept_x_mean, intercept_y_mean, transformed_X, transformed_y, eigen_indices, summary_Xty, summary_yty, compute_pve, pve_type_code, nthreads) {
    .Call(`_BayesLinReg_blm_gibbs_eigen_block_rcpp_cpp`, residual_shape, residual_scale, iterations, burnin, thin, progress_callback, block_id, block_model, normal_shape, normal_scale, pi_alpha, pi_beta, spike_var_shape, spike_var_scale, global_scale, local_a, local_b, multi_gamma_list, multi_pi_alpha_list, multi_var_shape, multi_var_scale, learn_residual_var, fixed_residual_var, store_samples, store_coefficient_cov, effective_n, fit_intercept, intercept_x_mean, intercept_y_mean, transformed_X, transformed_y, eigen_indices, summary_Xty, summary_yty, compute_pve, pve_type_code, nthreads)
}

