# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

blm_gibbs_rcpp_cpp <- function(y, X, prior_var, residual_shape, residual_scale, iterations, burnin, thin, progress_callback, use_spike_slab, pi_alpha, pi_beta) {
    .Call(`_blm_blm_gibbs_rcpp_cpp`, y, X, prior_var, residual_shape, residual_scale, iterations, burnin, thin, progress_callback, use_spike_slab, pi_alpha, pi_beta)
}

